stages:
  prepare:
    cmd: python src/prepare.py --in_csv data/zameen-updated.csv --out_dir data/processed
    deps:
      - data/zameen-updated.csv
      - src/prepare.py
      - params.yaml
    outs:
      - data/processed/cleaned.csv

  features:
    cmd: python src/features.py --in_csv data/processed/cleaned.csv --out_dir data/processed
    deps:
      - data/processed/cleaned.csv
      - src/features.py
      - params.yaml
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv
      - models/feature_columns.pkl

  train:
    cmd: python src/train.py --data_dir data/processed --model_out models/model.pkl
    deps:
      - data/processed/X_train.csv
      - data/processed/y_train.csv
      - src/train.py
      - params.yaml
    outs:
      - models/model.pkl

  evaluate:
    cmd: python src/evaluate.py --data_dir data/processed --model models/model.pkl --out metrics/eval.json
    deps:
      - data/processed/X_test.csv
      - data/processed/y_test.csv
      - models/model.pkl
      - src/evaluate.py
    metrics:
      - metrics/eval.json:
          cache: false
